language: c

sudo: false

before_script:
- chmod +x make-release.sh

script:
- ./make-release.sh

notifications:
  email:
    on_failure: always
    on_success: change
    notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c7874d7465fcff57f111
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
